# docker-compose.yml

version: "3.8"
services:
  road-surface-detection:
    build: .
    container_name: road-surface-detection
    volumes:
      - ./data:/data:rw
    command: ["python", "main.py"]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu] # enable GPU
