# docker-compose.yml

version: "3.8"
services:
  road-surface-detection:
    build: .
    container_name: road-surface-detection
    volumes:
      - ./data:/data:rw
    environment:
      - MODE=predict  # predict || train
    command: ["python", "main.py"]
