// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDKAlIJS15g6faLkdU0EJ2RnoKucdWoRA',
    appId: '1:987974893847:ios:267e6d2c73dea628b6f752',
    messagingSenderId: '987974893847',
    projectId: 'bikehero-1ed9f',
    storageBucket: 'bikehero-1ed9f.appspot.com',
    iosBundleId: 'dk.cct5group502.bikehero',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWqz8GLYEEMy-UfMGmxGbcGvvM5R_249k',
    appId: '1:987974893847:web:1cdb437073969dabb6f752',
    messagingSenderId: '987974893847',
    projectId: 'bikehero-1ed9f',
    authDomain: 'bikehero-1ed9f.firebaseapp.com',
    storageBucket: 'bikehero-1ed9f.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDKAlIJS15g6faLkdU0EJ2RnoKucdWoRA',
    appId: '1:987974893847:ios:267e6d2c73dea628b6f752',
    messagingSenderId: '987974893847',
    projectId: 'bikehero-1ed9f',
    storageBucket: 'bikehero-1ed9f.appspot.com',
    iosBundleId: 'dk.cct5group502.bikehero',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOATfitLAQ2HzjGYq6694d6WG5R8xsZzE',
    appId: '1:987974893847:android:b8b82f72102712fbb6f752',
    messagingSenderId: '987974893847',
    projectId: 'bikehero-1ed9f',
    storageBucket: 'bikehero-1ed9f.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWqz8GLYEEMy-UfMGmxGbcGvvM5R_249k',
    appId: '1:987974893847:web:e8d214a3e285dbeeb6f752',
    messagingSenderId: '987974893847',
    projectId: 'bikehero-1ed9f',
    authDomain: 'bikehero-1ed9f.firebaseapp.com',
    storageBucket: 'bikehero-1ed9f.appspot.com',
  );

}